apiVersion: v1
kind: Service
metadata:
  name: cpu-ram-monitor
spec:
  selector:
    app: cpu-ram-monitor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flask-ui
spec:
  selector:
    app: flask-ui
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
